using System;
using System.Collections.Generic;
using System.Text;

namespace Imago.Models.Enum
{
    public enum SkillType
    {
        Unbekannt = 0,
        Alchemie = 1,
        Anatomie = 2,
        Anfuehren = 3,
        Armbrueste = 4,
        Ausdruck = 5,
        Ausweichen = 6,
        Bewusstsein = 7,
        Blasrohre = 8,
        Boegen = 9,
        Chaos = 10,
        Dolche = 11,
        Einfalt = 12,
        Einschuechtern = 13,
        Ekstase = 14,
        Empathie = 15,
        Gesellschafter = 16,
        Hiebwaffen = 17,
        Heiler = 18,
        Klettern = 19,
        Koerperbeherrschung = 20,
        Kontrolle = 21,
        Laufen = 22,
        Literatur = 23,
        Leere = 24,
        Manipulation = 25,
        Materie = 26,
        Mathematik = 27,
        Naturkunde = 28,
        Philosophie = 29,
        Physik = 30,
        Reiten = 31,
        Schilde = 32,
        Schleichen = 33,
        Schleuder = 34,
        Schwerter = 35,
        Schwimmen = 36,
        Sicherheit = 37,
        SozialeAdaption = 38,
        Soziologie = 39,
        Sphaerologie = 40,
        Sprache = 41,
        Springen = 42,
        SpurenLesen = 43,
        StaebeSpeere = 44,
        Strategie = 45,
        Struktur = 46,
        Tanzen = 47,
        Taschendiebstahl = 48,
        Verbergen = 49,
        Verkleiden = 50,
        Verstecken = 51,
        Waffenlos = 52,
        WirtschaftRecht = 53,
        Wurfgeschosse = 54,
        Wurfwaffen = 55,
        Wundscher = 56,
        Zweihaender = 57,
    }
}