using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Text;
using ImagoApp.Application.Models;
using ImagoApp.Shared.Enums;
using Newtonsoft.Json;

namespace ImagoApp.Application.Services
{
    public interface ICharacterCreationService
    {
        CharacterModel CreateNewCharacter();
        string GetRandomName();
    }

    public class CharacterCreationService : ICharacterCreationService
    {
        private readonly Random _randome = new Random();
        private readonly List<string> _names = new List<string>()
        {
            "Abraham",
            "Adalbert",
            "Adam",
            "Adelard",
            "Adelheid",
            "Adelheidis",
            "Adelheit",
            "Adheimar",
            "Adolf",
            "Aegelnoth",
            "Aegidius",
            "Aelfric",
            "Agnes",
            "Alanus",
            "Albert",
            "Albertus",
            "Albrecht",
            "Aleidis",
            "Alexander",
            "Alfons",
            "Amalrich",
            "Amury",
            "Andreas",
            "Angela",
            "Anna",
            "Anno",
            "Anselm",
            "Ansgar",
            "Anshelmus",
            "Antonius",
            "Aribert",
            "Arnald",
            "Arnold",
            "Arnoldus",
            "Arnulf",
            "Arthur",
            "Artur",
            "Augustinus",
            "Ava",
            "Baldemarus",
            "Baldrich",
            "Balduin",
            "Baldwin",
            "Barbara",
            "Bartholomaeus",
            "Beatrix",
            "Begina",
            "Bela",
            "Belanca",
            "Benedict",
            "Benjamin",
            "Berard",
            "Berengar",
            "Berengaria",
            "Berger",
            "Berhdoldus",
            "Bernardus",
            "Bernward",
            "Berta",
            "Bertha",
            "Berthold",
            "Bertolf",
            "Bertram",
            "Berwelfus",
            "Bianca",
            "Bigela",
            "Billung",
            "Birgitta",
            "Biz",
            "Blanchefleur",
            "Blancheflor",
            "Blanchfleur",
            "Blondl",
            "Bohemund",
            "Bonames",
            "Boso",
            "Bredelin",
            "Brigitte",
            "Brunhilde",
            "Bruno",
            "Bube",
            "Burchard",
            "Burkardus",
            "Burkhard",
            "Caesarius",
            "Camilla",
            "Carissima",
            "Carl",
            "Carl-Otto",
            "Chlodhard",
            "Chlodhilde",
            "Christian",
            "Christina",
            "Christine",
            "Christoph",
            "Chunegundis",
            "Ciprianus",
            "Clementia",
            "Coletta",
            "Colin",
            "Crippin",
            "Cristianus",
            "Cristina",
            "Cuno",
            "Cunradus",
            "Curt",
            "Dagmar",
            "Dammo",
            "Daniel",
            "David",
            "Deigenhardus",
            "Demud",
            "Detmud",
            "Didericus",
            "Dieter",
            "Diethard",
            "Dietrich",
            "Dimarus",
            "Ditmarus",
            "Ditwinus",
            "Dominicus",
            "Dorothea",
            "Dudo",
            "Eberhard",
            "Eberhardus",
            "Eberold",
            "Eberwin",
            "Eckard",
            "Eckardus",
            "Eckberd",
            "Eckehard",
            "Edgar",
            "Edmund",
            "Eduard",
            "Eginolf",
            "Eike",
            "Einhard",
            "Einolfus",
            "Eleonore",
            "Elisabeth",
            "Embrico",
            "Emelricus",
            "Emercho",
            "Emich",
            "Emicho",
            "Emil",
            "Emma",
            "Emmerich",
            "Endemannus",
            "Engelbert",
            "Enolf",
            "Ensfried",
            "Enzio",
            "Erich",
            "Ermenoldus",
            "Everwinus",
            "Ezzelino",
            "Fabian",
            "Feist",
            "Ferdinand",
            "Filmann",
            "Flordelis",
            "Florian",
            "Franciscus",
            "Frank",
            "Frascha",
            "Fridebertus",
            "Fridebraht",
            "Fridericus",
            "Friedrich",
            "Fuchs",
            "Fulk",
            "Gallus",
            "Gebhard",
            "Gelfradus",
            "Georg",
            "Gerberga",
            "Gerbertus",
            "Gerbodo",
            "Gerbotho",
            "Gerda",
            "Gerhard",
            "Gerhardus",
            "Gerlach",
            "Gerlacus",
            "Gernandus",
            "Gertrud",
            "Gertrudis",
            "Gieselbert",
            "Gisela",
            "Giselberdus",
            "Giselbert",
            "Giso",
            "Godesmannus",
            "Godscalcus",
            "Gottfried",
            "Gotwinus",
            "Grethe",
            "Guda",
            "Gunter",
            "Gunterus",
            "Guntramus",
            "Gunzelinus",
            "Günther",
            "Halmann",
            "Hans",
            "Hapertus",
            "Harpernus",
            "Hartmann",
            "Hartmannus",
            "Hartmud",
            "Hartmudus",
            "Hartmut",
            "Hartrad",
            "Hedewigis",
            "Hedwig",
            "Heidenreich",
            "Heidindrudis",
            "Heidolfus",
            "Heilica",
            "Heilmann",
            "Heinrich",
            "Heinricus",
            "Helena",
            "Helene",
            "Helfrich",
            "Helfricus",
            "Hemma",
            "Herburgis",
            "Hermann",
            "Hermannus",
            "Herrad",
            "Hertwicus",
            "Hetzkinus",
            "Hildebert",
            "Hildebold",
            "Hildebrand",
            "Hildebrandus",
            "Hildegard",
            "Hilging",
            "Hiltgunt",
            "Hrosvit",
            "Hubert",
            "Hugo",
            "Humbert",
            "Hupertus",
            "Huste",
            "Héloise",
            "Ida",
            "Imagina",
            "Immanuel",
            "Imperatrix",
            "Ingeborg",
            "Ingebrand",
            "Ingrid",
            "Irene",
            "Iris",
            "Irmgard",
            "Isaak",
            "Isabella",
            "Isenbard",
            "Ivvanus",
            "Jakob",
            "Joachim",
            "Jobst",
            "Jofridus",
            "Johann",
            "Johanna",
            "Johannes",
            "Johannes:",
            "Jordanes",
            "Joseph",
            "Judith",
            "Julian",
            "Juliana",
            "Juta",
            "Jutta",
            "Karl",
            "Kasimir",
            "Katharina",
            "Katherine",
            "Kindel",
            "Klara",
            "Klaus",
            "Konrad",
            "Konradin",
            "Konstantin",
            "Konstanze",
            "Kraft",
            "Kunigunde",
            "Lambert",
            "Lazarus",
            "Lentfridus",
            "Leonhard",
            "Leopold",
            "Lerekopp",
            "Lipmann",
            "Liukardis",
            "Liutgard",
            "Loretta",
            "Lothar",
            "Lucardis",
            "Lucas",
            "Ludewicus",
            "Ludmilla",
            "Ludoldus",
            "Ludolf",
            "Ludolph",
            "Ludwig",
            "Lufridus",
            "Lugardis",
            "Luitfridus",
            "Luitgart",
            "Luitpold",
            "Magdalena",
            "Maginulf",
            "Magnus",
            "Malachias",
            "Manegold",
            "Manfred",
            "Manna",
            "Manuel",
            "Maren",
            "Margarete",
            "Margarethe",
            "Maria",
            "Markus",
            "Markward",
            "Marquard",
            "Marquardus",
            "Marsilius",
            "Martin",
            "Mathilde",
            "Matthaeus",
            "Matthias",
            "Mechtild",
            "Meffridus",
            "Meiger",
            "Meinfridus",
            "Meingotus",
            "Melisande",
            "Mengotus",
            "Methild",
            "Methildis",
            "Meusewin",
            "Michael",
            "Minnemann",
            "Namegud",
            "Neidhart",
            "Nibelungus",
            "Nicolaus",
            "Nidungus",
            "Nikolaus",
            "Noah",
            "Odo",
            "Olaf",
            "Olivo",
            "Ortolfus",
            "Ortwinus",
            "Otto",
            "Ottokar",
            "Pantaleon",
            "Paris",
            "Paul",
            "Peter",
            "Pether",
            "Petrissa",
            "Petrus",
            "Philipp",
            "Philippa",
            "Philippus",
            "Poppo",
            "Rainald",
            "Rebecca",
            "Reinboldus",
            "Reinhardt",
            "Relindis",
            "Rembold",
            "Richard",
            "Richina",
            "Richwin",
            "Ripertus",
            "Robert",
            "Robin",
            "Roger",
            "Rorich",
            "Roricus",
            "Rosche",
            "Rubertus",
            "Ruckelin",
            "Rudegerus",
            "Rudolf",
            "Rudolfus",
            "Rudwin",
            "Ruprecht",
            "Rutger",
            "Ruth",
            "Ruthardus",
            "Ruther",
            "Rüdiger",
            "Sabine",
            "Salentin",
            "Salman",
            "Savelad",
            "Schavart",
            "Schelm",
            "Selvaggia",
            "Sibert",
            "Sibertus",
            "Sibodo",
            "Siboldus",
            "Sibragtus",
            "Sibratus",
            "Siegeboto",
            "Siegfried",
            "Sifridus",
            "Sigenandus",
            "Sigismund",
            "Simon",
            "Sophia",
            "Stelin",
            "Stephan",
            "Swikerus",
            "Theobald",
            "Theoderich",
            "Theodericus",
            "Theodor",
            "Thilmann",
            "Thomas",
            "Tragebodo",
            "Truschel",
            "Udo",
            "Ulbert",
            "Ulrich",
            "Ulricus",
            "Ursel",
            "Ursula",
            "Valentin",
            "Veronika",
            "Vinzenz",
            "Violante",
            "Vivelin",
            "Volker",
            "Volmar",
            "Walburga",
            "Waldemar",
            "Walpurga",
            "Walram",
            "Walter",
            "Waltraut",
            "Wecelo",
            "Wenzel",
            "Werner",
            "Wernerus",
            "Wibert",
            "Widars",
            "Widradus",
            "Wigandus",
            "Wikenand",
            "Wikerus",
            "Wilderich",
            "Wilhelm",
            "Wilhelmus",
            "Willeburg",
            "Winand",
            "Wintherus",
            "Wirich",
            "Withekindus",
            "Wolfger",
            "Wolfram",
            "Wortwinus",
            "Yngelen",
            "Zolner"
        };

        public string GetRandomName()
        {
            return _names[_randome.Next(0, _names.Count - 1)];
        }

        public CharacterModel CreateNewCharacter()
        {
            var character = new CharacterModel
            {
                Attributes = CreateAttributes(),
                SkillGroups = new List<SkillGroupModel>(),
                Guid = Guid.NewGuid(),
                CreatedAt = DateTime.Now,
                OpenAttributeIncreases = new ObservableCollection<SkillGroupModelType>(),
                BodyParts = CreateBodyParts(),
                Weapons = new ObservableCollection<WeaponModel>(),
                EquippedItems = new ObservableCollection<EquipableItemModel>(),
                BloodCarrier = new ObservableCollection<BloodCarrierModel>()
            };

            //add skillgroups
            character.SkillGroups.Add(CreateSkillGroups(SkillGroupModelType.Nahkampf));
            character.SkillGroups.Add(CreateSkillGroups(SkillGroupModelType.Heimlichkeit));
            character.SkillGroups.Add(CreateSkillGroups(SkillGroupModelType.Fernkampf));
            character.SkillGroups.Add(CreateSkillGroups(SkillGroupModelType.Bewegung));
            character.SkillGroups.Add(CreateSkillGroups(SkillGroupModelType.Handwerk));
            character.SkillGroups.Add(CreateSkillGroups(SkillGroupModelType.Soziales));
            character.SkillGroups.Add(CreateSkillGroups(SkillGroupModelType.Webkunst));
            character.SkillGroups.Add(CreateSkillGroups(SkillGroupModelType.Wissenschaft));

            return character;
        }

        private List<BodyPartModel> CreateBodyParts()
        {
            return new List<BodyPartModel>
            {
                new BodyPartModel(BodyPartType.Kopf, new ObservableCollection<ArmorPartModelModel>()) { CurrentHitpointsPercentage = 1},
                new BodyPartModel(BodyPartType.Torso, new ObservableCollection<ArmorPartModelModel>()){ CurrentHitpointsPercentage = 1},
                new BodyPartModel(BodyPartType.ArmLinks, new ObservableCollection<ArmorPartModelModel>()){ CurrentHitpointsPercentage = 1},
                new BodyPartModel(BodyPartType.ArmRechts, new ObservableCollection<ArmorPartModelModel>()){ CurrentHitpointsPercentage = 1},
                new BodyPartModel(BodyPartType.BeinLinks, new ObservableCollection<ArmorPartModelModel>()){ CurrentHitpointsPercentage = 1},
                new BodyPartModel(BodyPartType.BeinRechts, new ObservableCollection<ArmorPartModelModel>()){ CurrentHitpointsPercentage = 1}
            };
        }

        private List<AttributeModel> CreateAttributes()
        {
            return new List<AttributeModel>
            {
                new AttributeModel(AttributeType.Staerke) ,
                new AttributeModel(AttributeType.Geschicklichkeit) ,
                new AttributeModel(AttributeType.Konstitution),
                new AttributeModel(AttributeType.Intelligenz) ,
                new AttributeModel(AttributeType.Willenskraft),
                new AttributeModel(AttributeType.Charisma) ,
                new AttributeModel(AttributeType.Wahrnehmung)
            };
        }

        private SkillGroupModel CreateSkillGroups(SkillGroupModelType modelType)
        {
            var skillGroup = new SkillGroupModel(modelType)
            {
                Skills = CreateSkills(modelType)
            };

            return skillGroup;
        }

        private List<SkillModel> CreateSkills(SkillGroupModelType groupModelType)
        {
            switch (groupModelType)
            {
                case SkillGroupModelType.Bewegung:
                    return new List<SkillModel>
                    {
                        new SkillModel(SkillModelType.Ausweichen),
                        new SkillModel(SkillModelType.Klettern),
                        new SkillModel(SkillModelType.Koerperbeherrschung),
                        new SkillModel(SkillModelType.Laufen),
                        new SkillModel(SkillModelType.Reiten),
                        new SkillModel(SkillModelType.Schwimmen),
                        new SkillModel(SkillModelType.Springen),
                        new SkillModel(SkillModelType.Tanzen)
                    };
                case SkillGroupModelType.Nahkampf:
                    return new List<SkillModel>
                    {
                        new SkillModel(SkillModelType.Dolche) ,
                        new SkillModel(SkillModelType.Hiebwaffen),
                        new SkillModel(SkillModelType.Schilde),
                        new SkillModel(SkillModelType.Schwerter),
                        new SkillModel(SkillModelType.StaebeSpeere),
                        new SkillModel(SkillModelType.Waffenlos),
                        new SkillModel(SkillModelType.Zweihaender),
                    };
                case SkillGroupModelType.Heimlichkeit:
                    return new List<SkillModel>
                    {
                        new SkillModel(SkillModelType.Schleichen),
                        new SkillModel(SkillModelType.Sicherheit),
                        new SkillModel(SkillModelType.SpurenLesen),
                        new SkillModel(SkillModelType.Taschendiebstahl),
                        new SkillModel(SkillModelType.Verstecken),
                        new SkillModel(SkillModelType.Verbergen),
                        new SkillModel(SkillModelType.Verkleiden),
                    };
                case SkillGroupModelType.Fernkampf:
                    return new List<SkillModel>
                    {
                        new SkillModel(SkillModelType.Armbrueste),
                        new SkillModel(SkillModelType.Blasrohre),
                        new SkillModel(SkillModelType.Boegen),
                        new SkillModel(SkillModelType.Schleuder),
                        new SkillModel(SkillModelType.Wurfgeschosse),
                        new SkillModel(SkillModelType.Wurfwaffen),
                    };
                case SkillGroupModelType.Webkunst:
                    return new List<SkillModel>
                    {
                        new SkillModel(SkillModelType.Bewusstsein),
                        new SkillModel(SkillModelType.Chaos),
                        new SkillModel(SkillModelType.Einfalt),
                        new SkillModel(SkillModelType.Ekstase),
                        new SkillModel(SkillModelType.Kontrolle),
                        new SkillModel(SkillModelType.Leere),
                        new SkillModel(SkillModelType.Materie),
                        new SkillModel(SkillModelType.Struktur),
                    };
                case SkillGroupModelType.Wissenschaft:
                    return new List<SkillModel>
                    {
                        new SkillModel(SkillModelType.Anatomie),
                        new SkillModel(SkillModelType.Literatur),
                        new SkillModel(SkillModelType.Mathematik),
                        new SkillModel(SkillModelType.Philosophie),
                        new SkillModel(SkillModelType.Physik),
                        new SkillModel(SkillModelType.Soziologie),
                        new SkillModel(SkillModelType.Sphaerologie),
                        new SkillModel(SkillModelType.WirtschaftRecht),
                    };
                case SkillGroupModelType.Handwerk:
                    return new List<SkillModel>
                    {
                        new SkillModel(SkillModelType.Alchemie),
                        new SkillModel(SkillModelType.Heiler),
                        new SkillModel(SkillModelType.Naturkunde),
                        new SkillModel(SkillModelType.Sprache),
                        new SkillModel(SkillModelType.Strategie),
                        new SkillModel(SkillModelType.Wundscher),
                    };
                case SkillGroupModelType.Soziales:
                    return new List<SkillModel>
                    {
                        new SkillModel(SkillModelType.Anfuehren),
                        new SkillModel(SkillModelType.Ausdruck),
                        new SkillModel(SkillModelType.Einschuechtern),
                        new SkillModel(SkillModelType.Empathie),
                        new SkillModel(SkillModelType.Gesellschafter),
                        new SkillModel(SkillModelType.Manipulation),
                        new SkillModel(SkillModelType.SozialeAdaption),
                    };
                default:
                    throw new ArgumentOutOfRangeException(nameof(groupModelType), groupModelType, null);
            }

        }
    }
}
